[package]
name = "walletd_bitcoin"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_bitcoin"
path = "src/lib.rs"

[dependencies]

walletd_coins = {path = "../"}
walletd_bip39 = {path = "../../mnemonics/bip39"}
walletd_hd_keys = {path = "../../hd_keys"}
walletd_cryptowallet = {path = "../../cryptowallet"}

base58 = { version = "0.2.0" }
bech32 = { version = "0.9.1"}
bitcoincore-rpc = "0.16.0"
reqwest = { version = "0.11", features = ["json"] }
ripemd = "0.1.3"
sha2 = { version = "0.10.6", default-features = false }