[package]
name = "walletd_bitcoin"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_bitcoin"
path = "src/lib.rs"

[dependencies]

walletd_coins = {path = "../"}
walletd_bip39 = {path = "../../mnemonics/bip39"}
walletd_hd_keys = {path = "../../hd_keys"}

base58 = { version = "0.2.0" }
bech32 = { version = "0.9.1"}
bitcoincore-rpc = "0.16.0"

libsecp256k1 = { version = "0.7.1" }
reqwest = { version = "0.11", features = ["blocking", "json"] }

ripemd = "0.1.3"
sha2 = { version = "0.10.6", default-features = false }
serde_json = "1.0"
serde = "1.0.148"
