[package]
name = "walletd_hd_keys"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_hd_keys"
path = "src/lib.rs"

[dependencies]

walletd_coins = {path = "../coins"}

base58 = { version = "0.1" }
bitcoincore-rpc = "0.16.0"
bitcoincore-rpc-json = "0.16.0"
bitvec = { version = "0.17.4" }
crc = { version = "1.8.1" }
curve25519-dalek = { version = "2.1.0" }
debug_print = {version = "1.0.0"}
env_logger = "0.9"
futures = "0.3" 
hex = { version = "0.4.2" }
hmac = { version = "0.7.0" }
libsecp256k1 = { version = "0.3.5", default-features = false, features = ["hmac"] }
mini-redis = "0.4"
pbkdf2 = { version = "0.3.0", features=["parallel"], default-features = false }
rand = { version = "0.7" }
reqwest = { version = "0.11", features = ["json"] }
ripemd160 = { version = "0.8", default-features = false }
sha2 = { version = "0.8", default-features = false }
solana-client = "1.14.7"
tiny-bip39 = "0.8.2"
tokio = { version = "1", features = ["full"] }
web3 = "0.17.0"


