[package]
name = "walletd_ethereum"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_ethereum"
path = "src/lib.rs"

[dependencies]

walletd_bip39 = {path = "../../mnemonics/bip39"}
walletd_coins = {path = "../"}
walletd_hd_keys = {path = "../../hd_keys"}

hex = "0.4.3"
libsecp256k1 = { version = "0.7.1" }
keccak-hash = "0.10.0"
tiny-keccak = { version = "2.0.2" }
tokio = { version = "1", features = ["full"] }
web3 = "0.18.0"