[package]
name = "walletd_ethereum"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_ethereum"
path = "src/lib.rs"

[dependencies]

walletd_coins = {path = "../"}
walletd_bip39 = {path = "../../mnemonics/bip39"}

tokio = { version = "1", features = ["full"] }
web3 = "0.17.0"