[package]
name = "walletd_solana"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletd_solana"
path = "src/lib.rs"

[dependencies]

walletd_bip39 = {path = "../../mnemonics/bip39"}
walletd_coins = {path = "../"}
walletd_cryptowallet = {path = "../../cryptowallet"}
walletd_hd_keys = {path = "../../hd_keys"}

solana-client = "1.14.7"