[package]
name = "walletd_bitcoin_basic"
version = "0.1.0"
edition = "2021"

[dependencies]
walletd_bitcoin = {path = "../../"}

hex = "0.4.3"
secp256k1 = {version = "0.25.0", features = ["rand-std"]}